USE_CUDNN := 1
USE_OPENCV := 1
OPENCV_VERSION := 4
WITH_PYTHON_LAYER := 1
CPU_ONLY := 0

CUDA_DIR := /usr/local/cuda-10.2

PYTHON_INCLUDE := /usr/include/python3.10 \
    /usr/lib/python3/dist-packages/numpy/core/include

PYTHON_LIB := /usr/lib
PYTHON_LIBRARIES := boost_python310 python3.10

INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial /usr/include/opencv4
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/hdf5/serial

BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
Q ?= @

